
[global]
highlight       = "#cfc1ba"
frame_color     = "#2c363c"
separator_color = frame

[urgency_low]
background      = "#f0edec"
foreground      = "#2c363c"
timeout         = 1

[urgency_normal]
background      = "#f0edec"
foreground      = "#2c363c"
timeout         = 3

[urgency_critical]
background      = "#2c363c"
foreground      = "#f0edec"
frame_color     = "#f0edec"
timeout         = 12
