import = ["/home/jaboi/.config/alacritty/zenwritten_light.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "MartianMono Nerd Font"

[window]
opacity = 1

[window.padding]
x = 3
y = 3
